### ISSUE TITLE
Is it possible to re-fetch some days ?

### ISSUE THREAD

**Issue by supermamie** [SimonMellerin/Pilea#25]
I just noticed that I have no data for 2 days last week, is it possible to force a re-fetch for those days ?

![image](https://user-images.githubusercontent.com/693751/66461934-571def00-ea7a-11e9-9b9e-d08515ecc76a.png)

**Comment by SimonMellerin** [comment]
or now, you can't do that from UI but you can do it via ssh
in the pilea directory :

```bin/console pilea:fetch-data true 2018-02-13```

But, for technical reason, after you refresh a day, you have to also refresh the next sunday and the last day of month

In your case, as 04/10/2019 is a friday :
```bin/console pilea:fetch-data true 2019-10-04```
```bin/console pilea:fetch-data true 2019-10-06```
```bin/console pilea:fetch-data true 2019-10-31```

The last line is not necessary since the 31/10/2019 is in the future

cheers

**Comment by SimonMellerin** [comment]
Be aware that you can't refresh meteo data after 15 days

**Comment by supermamie** [comment]
I tried without success, then checked on enedis.fr and there is no data for those 2 days.
